name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover

  build_and_deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/samgekko/dockerlab:latest .
          docker push ghcr.io/samgekko/dockerlab:latest

      - name: Run application in Docker container
        run: docker run ghcr.io/samgekko/dockerlab:latest

  task_1:
    runs-on: ubuntu-latest

    needs: build_and_deploy

    steps:
      - name: pyapp
        run: |
          docker run ghcr.io/samgekko/dockerlab:latest python app.py "${{ env.INPUT_ENV_VARIABLE }}" > result.txt
        env:
          INPUT_ENV_VARIABLE: ${{ secrets.CHAR_VARIABLE }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: result.txt
