name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    stages:
      - test
      - build_and_deploy

    # Этап 1: Тестирование
    - name: Test
      stage: test
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: python -m unittest discover

    # Этап 2: Сборка и развертывание
    - name: Build and Deploy
      stage: build_and_deploy
      needs: test
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker
          uses: actions/setup-docker@v2

        - name: Build and push Docker image
          run: |
            docker build -t ghcr.io/SamGekko/dockerlab:latest .
            docker push ghcr.io/SamGekko/dockerlab:latest

        - name: Run application in Docker container
          run: docker run ghcr.io/SamGekko/dockerlab:latest

        # Задача 1: Запуск скрипта с параметрами и сохранение результатов в артефактах
        - name: Task 1
          run: |
            docker run ghcr.io/SamGekko/dockerlab:latest python app.py "${{ inputs.env_variable }}" > result.txt

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
            name: results
            path: result.txt

